name: flutter_app_template_atoms
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.2
  audioplayers: ^6.0.0
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.9.3+1
  awesome_notifications_core: ^0.9.3
  # Adds the Cupertino Icons font.
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter

  flutter_vibrate: ^1.3.0
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.0.8
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^9.2.0
  google_fonts: ^6.2.1
    # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  shared_preferences: ^2.2.3
  vibration: ^1.8.4
  wakelock_plus: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.8.2
flutter:

  uses-material-design: true
  assets:
    - assets/

