name: word_link
description: "Help to learn new language"
publish_to: 'none'
repository: https://github.com/guyluz11/language_app

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_text_kit:
    git:
      url: https://github.com/guyluz11/Animated-Text-Kit.git
  animated_toggle_switch: ^0.8.4
  audioplayers: ^6.1.0
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # Adds the Cupertino Icons font.
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
<<<<<<< HEAD
    
=======

>>>>>>> d37aa67c59ad98b0da4316d4ef85ffd5d570c160
  flutter_tts: ^4.2.2
  google_mlkit_translation: ^0.13.0

  flutter_svg: ^2.0.17
  flutter_tts: ^4.2.2
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.2.10
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
    # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.5.0
  shared_preferences: ^2.3.5
  universal_io: ^2.2.2
  uuid: ^4.5.1
  vibration: ^3.1.3
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.3.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/


# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/logo.png"

  android: "ic_launcher"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
#  adaptive_icon_monochrome: "assets/logo_with_bg.png"

  ios: true
  image_path_ios: "assets/logo.png"
  # image_path_ios: "assets/icon/logo.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/logo_with_bg.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/logo_with_bg.png"
