name: word_link
description: "Help to learn new language"
publish_to: 'none'
repository: https://github.com/guyluz11/language_app

version: 1.0.0+1

environment:
  sdk: ''>=3.4.4 <4.0.0'

dependencies:
  animated_toggle_switch: ^0.8.4
  audioplayers: ^6.1.0
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.10.0
  awesome_notifications_core: ^0.10.0
  # Adds the Cupertino Icons font.
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.2.10
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
    # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.5.0
  shared_preferences: ^2.3.5
  universal_io: ^2.2.2
  uuid: ^4.5.1
  vibration: ^2.0.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.3.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/words/polish_words.txt
