name: Android CD

on:
  push:
    branches: [ main ]

env:
  flutter_channel: 'stable'
  flutter_version: '3.32.4'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s "/Applications/Xcode_16.2.app"

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods and Prebuild for Simulator
        run: |
          cd ios
          pod install
          cd ..
          flutter build ios --simulator

      # Open ios simulator
      - uses: futureware-tech/simulator-action@v4
        with:
          model: 'iPhone 16 Plus'
          wait_for_boot: true

      # Run Flutter Integration Tests and take screenshots
      - name: Run Integration Tests on iOS Simulator
        run: flutter drive --driver=integration_driver/integration_test_driver.dart --target=integration_test/app_test.dart -d "iPhone 16 Plus"

      - name: Shut down iOS Simulator
        run: xcrun simctl shutdown all

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Set up Ruby for Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Fastlane
        run: gem install fastlane

      # Build and deploy using Fastlane
      - name: Build and deploy to Play Store
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
          APP_NAME_FOR_FOLDERS: ${{ secrets.APP_NAME_FOR_FOLDERS }}
        run: |
          # Decode the .jks file
          echo $ANDROID_KEYSTORE_BASE64 | base64 -d > /tmp/key.jks

          # Set google play json key
          echo $GOOGLE_PLAY_JSON_KEY > /tmp/file.json
          
          # Create key.properties
          cd android
          echo "$KEY_PROPERTIES" > key.properties
          
          export GITHUB_ACTIONS=true
          
          fastlane deploy