name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  flutter_channel: 'stable'
  flutter_version: '3.29.3'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      - uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'zulu'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analysis
        run: flutter analyze

      - name: Run iOS Fastlane
        run: fastlane ios deploy 