name: iOS CI

on:
  push:
    branches: [ main ]

env:
  flutter_channel: 'stable'
  flutter_version: '3.32.4'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
          flutter-version: ${{ env.flutter_version }}

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Open ios simulator
      - uses: futureware-tech/simulator-action@v4
        with:
          model: 'iPhone 16 Plus'
          wait_for_boot: true

      - name: Install CocoaPods and Prebuild for Simulator
        run: |
          cd ios
          pod install
          cd ..
          flutter build ios --simulator

      # Run Flutter Integration Tests and take screenshots
      - name: Run Integration Tests on iOS Simulator
        run: flutter drive --driver=integration_driver/integration_test_driver.dart --target=integration_test/app_test.dart -d "iPhone 16 Plus"

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Set up Ruby for Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Fastlane
        run: gem install fastlane

      # Build and deploy using Fastlane
      - name: Build and deploy to App Store
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_TOKEN: ${{ secrets.MATCH_GIT_TOKEN }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_NAME_FOR_FOLDERS: ${{ secrets.APP_NAME_FOR_FOLDERS }}
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > /tmp/app_store_key.p8
          cd ios
          export GITHUB_ACTIONS=true
          fastlane deploy